swagger: "2.0"
info:
  title: Microsserviço - Prontuário Animal
  version: 1.0.0
  description: API para gerenciar animais, histórico de consultas, exames e prontuários.

host: localhost:5000
basePath: /api
schemes:
  - http

securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header

security:
  - bearerAuth: []

paths:
  /animais:
    post:
      tags:
        - Animais
      summary: Cadastrar novo animal
      parameters:
        - in: body
          name: animal
          required: true
          schema:
            type: object
            required:
              - nome
              - tutor_nome
              - tutor_contato
            properties:
              nome:
                type: string
              tutor_nome:
                type: string
              tutor_contato:
                type: string
      responses:
        201:
          description: Animal criado com sucesso

  /animais/{animal_id}:
    get:
      tags:
        - Animais
      summary: Buscar animal por ID
      parameters:
        - name: animal_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Dados do animal
        404:
          description: Animal não encontrado
    delete:
      tags:
        - Animais
      summary: Excluir animal (se não tiver histórico médico)
      parameters:
        - name: animal_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Animal excluído
        403:
          description: Animal possui histórico e não pode ser excluído

  /animais/{animal_id}/inativar:
    put:
      tags:
        - Animais
      summary: Inativar animal
      parameters:
        - name: animal_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Animal inativado
        400:
          description: Animal não possui histórico médico

  /animais/{animal_id}/exists:
    get:
      tags:
        - Integração
      summary: Verifica se o animal existe
      parameters:
        - name: animal_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Animal encontrado
        404:
          description: Animal não encontrado

  /animais/{animal_id}/consultas:
    post:
      tags:
        - Consultas
      summary: Cadastrar consulta para animal
      parameters:
        - name: animal_id
          in: path
          required: true
          type: integer
        - in: body
          name: consulta
          required: true
          schema:
            type: object
            required:
              - data
              - tipo
              - status
            properties:
              data:
                type: string
              tipo:
                type: string
              status:
                type: string
              diagnostico:
                type: string
              tratamento:
                type: string
              cirurgia:
                type: string
              peso:
                type: number
      responses:
        201:
          description: Consulta registrada
    get:
      tags:
        - Consultas
      summary: Listar consultas do animal
      parameters:
        - name: animal_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Lista de consultas

  /animais/{animal_id}/exames:
    post:
      tags:
        - Exames
      summary: Registrar exame para animal
      parameters:
        - name: animal_id
          in: path
          required: true
          type: integer
        - in: body
          name: exame
          required: true
          schema:
            type: object
            required:
              - descricao
              - imagem_url
            properties:
              descricao:
                type: string
              imagem_url:
                type: string
      responses:
        201:
          description: Exame registrado
    get:
      tags:
        - Exames
      summary: Listar exames do animal
      parameters:
        - name: animal_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: Lista de exames
